# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Topic.destroy_all
Response.destroy_all

@admin = User.create!(username: 'Jackie', email: 'jackie@email.com', password: '123456')
@user1 = User.create!(username: 'Casey', email: 'casey@email.com', password: '123456')
@user2 = User.create!(username: 'Slater', email: 'slater@email.com', password: '123456')

puts "#{User.count} users created"

@topic1 = Topic.create!(topic: "Your character has always viewed the past with rose tinted glasses. Write about what happens when they're finally confronted with the truth.", user: @admin)
@topic2 = Topic.create!(topic: "Write a story about a character who's trying to fill an empty space, literally or metaphorically.", user: @admin)
@topic3 = Topic.create!(topic: "Write a story inspired by a piece of music (without using any lyrics).", user: @user1)
@topic4 = Topic.create!(topic: "Write about a character seeking forgiveness for something that happened in the past.", user: @user1)
@topic5 = Topic.create!(topic: "Write a story involving a character who cannot return home.", user: @user2)

puts "#{Topic.count} topics created"

@response1 = Response.create!(response: "Breathe in. Let your eyes close. Let your mind wander.
Think back to a time when you were happy as a child. There must have been times when you were happy.
Notice any tension in your forehead. Relax the muscles between your eyebrows.
The time when you were three and your parents took you to a water park. You were scared of the tallest slides, but you felt safe in Daddy's arms. You loved the bright pink flowers on your black swimsuit, the neon green ruffles around your waist. The river stone pathways bisecting the park, shaded by the arching branches of longleaf pines. Chlorine burned at the back of your nose. Water beaded on your skin and dripped from the pointed curls at the ends of your pigtails, chilling your shoulders where the drops made contact. But Daddy's skin was warm and the wiry hair of his chest tickled your face where you leaned against him.
Let your jaw go slack. Loosen your tongue inside your mouth.
The time when you were eight and your parents took you and your sister to Pizza Hut. You loved Pizza Hut, back when it was a destination, a sit-down restaurant where the waitresses smiled at you and gave you extra peppermints. It was your favorite place, the distinctive sloped roof and red sign inciting an almost pavlovian response each time your parents' car turned into the crumbling asphalt parking lot. Your mouth would begin to water and your stomach would grumble in anticipation of the soft crust, tangy sauce and chewy mozzarella that awaited you. This time, you were seated at the best table in the restaurant, the one right in the middle of the room, equidistant from the buffet on one side and the fountain drink machines on the other. Positioned so you could see each new pie exiting the kitchen on its way to the buffet, could be the first to grab a slice of every pizza that called to you.
Release any tension in your shoulders. Feel your belly expand as the air fills your lungs.
The time when you were ten and your mother took you shopping at the department store on the military base. It was the mid-nineties and long floral skirts were everything. You tried one on, lavender with white flowers. Beautiful. You turned left and right, admiring your reflection in the narrow dressing room mirror as Mariah Carey's latest single warbled softly through the speakers in the ceiling. You felt elegant, like a princess. You couldn't wait to open the chipped white door and show your mother.
Bring your awareness to your lower back. Feel your sits bones pressing into the floor.
Your teenage years, spending every weekend at the gym with your dad. Muscles burning as he pushed you harder on the bench press, corrected your form on your bicep curls. He only took you to the gym, not your mother or your sister, because you were Daddy's Girl. Your friends were all jealous of how close you were with your dad; the other men at the gym hid their smiles as they complimented your form and remarked on how they could never get their own daughters to spend so much time with them. Your dad was clearly doing something right.
Now hold the breath. Notice the sensation of your lungs filled with air.
Your high school graduation. You were valedictorian, so proud that all of your hard work had paid off. You picked your way up the steps on the side of the stage, careful not to trip in the high heels your mother had bought you for the ceremony. You approached the podium to make your speech, somber, dignified, in your black robe and mortarboard hat. Your shoulders were draped with a shining gold stole which matched the tassel hanging from the edge of your cap. You took a deep breath, brushed the dangling tassel away from your face. A camera flashed, the room went blurry. You smiled.
Slowly - slowly - begin to breathe out. Let the air slide from your lips.
Let it go, along with the memory of Daddy setting you down on the river rock path at the water park. He'd leaned over your shoulder, reaching one long arm out to point straight ahead. Look at Mommy. She was strolling away from you further up the path, dimpled thighs brushing together below a flowery blue swimsuit. You smiled, were about to call out to her, when Daddy spoke again. That's disgusting. Look at how terrible she looks. You were confused, sad - how could Mommy be disgusting? Look at her legs. So fat. They're not supposed to look like that.
Feel the pressure in your belly release as the breath flows out.
Your abdomen was the first place your mother's eyes always went when she took you shopping. You remember opening the dressing room door to show her that beautiful lavender skirt. She looked straight at your midsection, eyes drawn like magnets to the curve of your lower belly. Her nose scrunched and her lip curled, as though the sight of you smelled terrible. You need to start doing sit-ups. She didn't buy you the skirt.
Let your shoulders drop as you continue to exhale.
Your shoulders had been hunched around your ears until you left the Pizza Hut, mortified, wishing you could disappear. You and your sister had been arguing about who would get the last slice of the cinnamon-drizzled dessert pizza, when your father reached his left hand back and swung it out across the table. Neither one of you needs the calories! He slapped you both across the face and the entire restaurant went silent. I got them both on the same swing, two for the price of one! He told that story for years afterward.
Empty the lungs completely. Let go of any lingering tension.
The tension you felt, all the times you didn't want to be in the gym with your father. You wanted to be at home, watching TV with your sister, who never had to go to the gym with your dad, because she was thin. But you weren't, and your dad couldn't let you be disgusting. He'd make you stand behind the machines while he exercised, weighted plates sliding up on the pulleys and clattering back down, swapping out with you between sets. Remember - or rather, try not to remember - the time you interrupted one of his sets to ask if you could go home. His arm shot out, his fist wrapping around your jaw, cracking your head back against the whitewashed cinder block wall. His fingers, so strong from lifting weights every day, squeezing your face so hard you thought your teeth might break. The other men in the gym looked away, embarrassed, and continued their reps. You'll go home when we're done! But you'd never be done, because you could never be as thin as your sister. It felt like a betrayal when you found out about her eating disorder. She'd discovered the secret to avoiding your father's wrath, and she hadn't shared it with you.
Now, bring your awareness back to your fingers and toes.
It was the camera flash that made your vision blur at graduation. It was the giddiness of being up on a stage, about to speak in front of so many people, that made you dizzy. It wasn't the hunger gnawing away at you, the residual blood rush behind your eyes from the ten minutes you'd just spent in the ladies' room ridding yourself of the celebratory breakfast you'd gulped down with your family before the ceremony. When was the last time you'd eaten before that? Two days ago? Three? It didn't matter, because your stomach, underneath your billowing robe, was finally flat. Your hard work had paid off; your father could finally be proud of you. He posed for pictures with you after the ceremony, one arm around your shoulders, and suggested you keep the hat on but lose the robe. It's not flattering on you.
Well, you were almost happy. 
When you're ready, open your eyes.", user: @user1, topic: @topic1)
@Response2 = Response.create!(response: "I am spinning slowly in my tank, suspended in doped-up air, buoyant, bobbing. Piano music-- Beethoven? plays softly in the background. My eyes are closed, but if I opened them, I would see only pale yellow light enclosing me in a warm glow.
I like the piano music. It makes me feel calm. That, alongside the sedation. The Facility keeps mine light, because I prefer it that way, and because I am well-behaved. The Facility knows my ways, knows I don't misbehave. I have been here for a long time now. It must be years, though there is no sense of time. No calendar, no clock. Only the pale light washing over me, keeping me warm. 
This morning, the Facility reminded me that my son will visit me today. He comes every week, at the same time. While the staff prepare me for his visit, they tell me he is good to me, compared to most of the others in here, at the Blessed Home facility, whose families have forgotten them. I nod and smile gently, murmuring the right response. They think my mind is feeble, like so many in here. I cannot see outside my tank, but the Facility can see inside, so I stay locked inside my mind. They cannot see inside my mind. In my mind, I am not suspended in a tank of gas and air. I go away, far from here.
Where do I go? I go home, to my sprawling house in the countryside, with a red-tiled roof and ivy-covered archway, the mishmash of furniture and ornaments, collected over a lifetime, heavy with memories. For sixty years, my wife and I lived there, raised our child and grew old. We had a black cat with a white tummy called Cat Stevens. But then my wife died and my only son accused me of going senile.
The bell that signals that my sedation has stopped chimes. Soon, they will come to collect me. I stop spinning as the air thins and I float to the bottom of the tank. I wait.
A pop of glass opening, bright light seeps inside. A gentle hand the length of my body picks me up from under my arms and seats me in a dollhouse armchair. I watch as the giant girl in the Facility's uniform scrubs her hands in a sink as large as a swimming pool. She is a kind of nurse, I think. My wife was a nurse, though in our day, the Facility didn't exist. I am handed a pair of sunglasses while my eyes adjust to the natural light. 
“How are you feeling today, Mr Donnelly?” her voice booms.
I mumble something as she dresses me. When I first arrived, I was embarrassed by foreign hands touching my body, stripping me bare, clothing me in strange scratchy Facility clothes. But now, I am apathetic. Maybe it's the drugs. 
When I am presentable, she brings me to the visiting area. I sit in an armchair, more comfortable than the last, watching vast visitors speak to their doll-sized relatives. I once heard a story about a family who brought home their shrunken grandma from the Facility, only to have her chewed up by her once beloved dog.
My son comes into view, striding towards me with confident steps. I used to walk like that too, before I came to the Facility. He plants himself squarely in the visitor's chair, launching into a nervous segment on his drive here, and the audacity of other drivers, and how isn't it ridiculous that with all the technological advancements in the world, we still don't have cars that drive the middle class from A to B?
While he talks, I let my mind drift. I used to be angry at him for forcing me to come here. Of course, he needed consent, but the pressure, financial and emotional, forced my hand. He threw all kinds of arguments at me; overpopulation, nursing homes. I used to wonder if he wanted to punish me, if I was a bad father, if I shouted too much, if I pushed him too far, if he resented me. 
I don't wonder anymore. I don't do anything much. The end is coming soon; I can tell by the way my body submit to sedation. I asked them to lighten it, because I know I will sleep for a long time, soon. I want to comb over my memories of home, before I go on to whatever lies beyond. I wish I was going home. But I'll never go home again. 
***
The thirty-minute drive to my father's facility is the most inconvenient part of my week. I swear as I swerve around incompetent idiots, blaring the horn and flipping off scandalised old ladies who surely shouldn't have licenses anyway. It's amazing with all the advancements in technology, I still have to drive myself to get where I need to go. I take my anger out on the road, so that by the time I get to Blessed Home, I am wrung dry of emotion.
I first heard about it when my father was getting too senile to live at home, and we were looking at nursing homes for him. But the demand is competitive, the prices obscene, the facilities bad. I didn't want him to be abused and neglected, and he flat out refused to go to a nursing home. Pulled the “what would your mother think?” line too. 
Someone told me about this facility. They had seen it on the dark web. I brought my father here for a consultation. They welcomed us warmly, offered us coffee, spewed us with medical jargon. We toured the premises as they explained the basics of the technology, how it was possible to reduce the size of a person using extreme heat pressure to the size of a ragdoll, while preserving their body and mind. They showed us to a vault, where little old people bobbing in silver containers lined the walls, sleeping. They described the benefits - fewer drugs needed, less food, less waste, easier to manage large numbers of people, easy storage. They were sedated the majority of the time, woken at various intervals to eat, to exercise, to excrete.
He wasn't convinced. But because the nursing home was a no-go, it was easier to convince him to try. That was all we needed. Left with no other option, he signed his life away. I promised to visit him every week. I have never broken that promise. 
The facility is spotlessly white. The receptionist flashes me an expensive smile.
“Welcome to Blessed Home, Mr Donnelly. Go right ahead.”
They always have him ready to see me as soon as I arrive. During his former life, he was a big man, looming, powerful. A blue-collar labourer who wanted a better life for his son. His presence, hell, his shadow, used to scare me. Now, as I walk towards him, he is miniscule, deflated. He looks tired. He always looks tired.
I tell him about my week. He listens, or doesn't. I can't tell, because he nods and murmurs at the right times, but never asks me questions. I never ask him how he is doing. I know he does nothing. He goes back into the vat of drugged up air and bobs around for hours, days, left with nothing but his own fading memories and medicated slumber. 
Do I feel ashamed? I don't dwell on it for long enough to feel anything but relief. I don't have to sacrifice my life to look after him, or remortgage my house to fund his last years. I don't feel guilty, because I'm not alone. Thousands of families send their elderly, dying relatives to these facilities, which have sprung up all over the country. It's normalised now. So it must be OK.
At the end of our hour together, I always turn away, so I won't have to look at him being lifted like a baby back into the vault. I wonder if he ever misses his home, the old house with the rusty roof and overgrown garden, sold to pay the price to live in a tank. After drinking alone one evening, filled with morbid curiosity, I drove by. Bleary eyed, I noted a strange car in the driveway. The lawn was mowed, the roof replaced, the door painted a happy yellow. I wanted to stop and knock on the door. But I didn't. I looked away, eyes on the road, and kept driving. 
He must know that he will never see it again. He will die in this godforsaken place I put him in. The irony of naming this little piece of hell *Blessed Home* makes me shiver. I wonder if his mind is past the point of knowing, or if he knows more than he lets on. I could ruminate on whether I did the right thing, but what good would it do?
The Blessed Home facility grows smaller as I drive away, and I forget, for another week at least.", user: @admin, topic: @topic5)
@response3 = Response.create!(response: "One is black.
My therapist suggested this activity, which I think is a waste of time. I'm not really very artistic.
Allie was. I was surprised by how well she could color, for her age, I mean. She didn't just scribble, she chose her colors carefully, she stayed in the lines, she even shaded, sometimes. She wasn't a savant but her pictures were better than other four-year-old kids'. Oh, how I loved her pictures.
Making this picture of my own is neither creative nor productive, but I must admit it is oddly satisfying. And it gives me something to do in church, when I don't want to talk to the people sitting next to me. I look like I'm focused, and they leave me alone, and when I hear someone in class share a myopic story about how they prayed and God helped them find their car keys, I just search for another One and keep my head down. Color in the circle, or the rectangle, or the triangle. Find the next segment. Try not to think about a loving, all-seeing, all-knowing God who would descend from His throne divine to help someone find their car keys, but allow my preschooler to suffer and die from an incurable childhood cancer.
One is black. It outlines everything. I do One first.
I think of her at the strangest moments. Like when I'm filling a bag of oatmeal from the bulk bin dispenser, and I remember her at age two, slipping away from me at Kroger and making her way to that same aisle which must have looked like a free candy dispensary. When I found her, she was full of chocolate covered raisins and peach rings. I was full of embarrassment and confusion over the predicament, so I just hoisted her atop my pregnant belly, handed a confused cashier a twenty and left.
The memory is so real and vivid that I turn to the shopping cart to retell it to her, and I remember she's gone. There's just the one sister now, a lone mitten without a mate, sitting in the cart, staring toward the school supplies and nibbling a thumbnail nervously. I don't tell her the story. We don't talk about Allie much. Even though my therapist says we should.
Two is brown. It brings to life the little doe, sitting in the forest, only it leaves behind the white spots and underbelly. Two is the dirt beneath the grass. Two are the trees.
Kendra is at the dentist. She's gotten four fillings in the past month, but one of them just won't stay in. Dentist said something about tight contacts, small mouth, I don't know, all I know is a few hours after she gets home the thing has popped right out again. I made Darrin take her. I can't go to the dentist anymore. I can't stand to see the scrubs and the implements. No amount of color-by-number can soothe that anxiety.
Meanwhile, I'm staring at the dining room table, hoping a fully prepared meal might miraculously appear there.
Two years ago, it seemed this table was, indeed, a purveyor of magically prepared meals. It was covered with homemade bread, cookies, and, mostly c,asseroles. My mother-in-law stacked those in the fridge and put whatever was closest at hand into the oven at 350 degrees. I put it on my fork and into my mouth mechanically, without tasting, because you still have to do mundane things, like feed yourself. You still have to do them, even when your child is dead.
You still have to feed yourself and your family years later, too. But the table isn't magic anymore.
Three is green. Grass and leaves.
I cry when I begin three, seeing the grass shoots come up from the dirt. I never knew grass could hurt, but it does, when you realize that time has passed, and grass is growing over your daughter's grave, even though it feels like just yesterday that it was a fresh mound. Wasn't it just last week she was healthy, three-and-a-half, zooming down a twirly slide? Wasn't it just last month that she held her new baby sister on her lap, pointing out the tiny facial features with a chubby finger?
Except it wasn't. That new baby is about to start preschool. In three days Kendra will be as old as Allie was when she died. And I'm terrified of what that means.
Four is pink. Delicate pink flowers. Just starting to bloom.
What happens when your youngest child grows older than your oldest child? There's no answer in a parenting book for that question. It isn't supposed to happen. We held space for Allie, but now I worry, somehow the space is gone. Like the white in my picture, which is rapidly disappearing. People assume, without asking, that Kendra is an only child. My mom has stopped saying Allie's name, for some reason. She's just...disappearing, and I wonder whether she left a trace in the world. But inside of me there's still a grave, six feet deep, and it will never be filled in.
Kendra starts preschool today. She's nervous, but I know she'll do great. She needs to be with other kids her age, it will be good for her.
Five is orange. It highlights the undersides of the leaves. Orange tulips.
I sit on the floor in the girls' room, coloring, imagining that Kendra is probably coloring too. I am obsolete, an adult who spends her hours shading in shapes, following a prescribed pattern to make mass-produced art. I am a thirty-year-old empty nester, a geriatric. Only that can't be true, because I have a four-year-old. Two of them, actually.
My therapist says I should think about getting a job. I want to tell her I have my hands full, but that would be a lie. I wish I had my hands full. Instead, I spend my precious alone hours wishing I wasn't alone. I color. I long to be needed, even if that need is to hold my baby girl's hair while she vomits bile, again and again. To stay awake, all night, because she can only fall asleep sitting on my lap. To watch her breathing get slower and slower because I was the one who pushed her into this world, and I needed to be the one to hold her hand when she was pulled out.
Six is yellow. The last color. It's mostly sunshine.
It was sunny, the day we buried Allie. The preacher said some bullshit about it being Allie smiling down on us, but I couldn't believe it. It just felt cruel, that good weather still existed. That the sun could shine down and warm me, but its warmth would never again reach her, because she was too far underground to feel it. She was cold. She would always be cold.
But, and I know it's really trite to say this, the sun kept coming up. The Earth kept spinning even though my beautiful, artistic, vivacious daughter was no longer on it. And the sun keeps coming up, and coming up, and soon I will have lived more revolutions on Earth since she left than I did while she was here, and entertaining that thought is like touching a hot stove and I can't do it.
I don't want to finish. I want to leave these white spaces, glaringly obvious to show that we aren't complete without her. That we never will be.
So, I leave the Six blank. ", user: @user1, topic: @topic2)
@response4 = Response.create!(response: "First and foremost, I just need to assert what was right and what was wrong. I think, before you can apologize for things you've done, you need to really isolate and evaluate exactly what you did wrong, and it's very rare that you, uh, you know, haven't done anything right in the midst of all you did wrong. So, I would like to assert that, yes, I made mistakes. I made many mistakes. I hurt people. Well, not people, but, you know, living things. I hurt living things and I hurt them by damaging their property and terrorizing them, and for that, I am very sorry, and I stand here, humbly, in front of you today, with my tail between my legs--literally--to say that I do apologize for the wrong I've done. Not for the right I've done, obviously, because I don't need to apologize for what I've done right, and I have done some things right, but I don't need to apologize for those things. Just the wrong things.
  Uh, but, uh, yeah, the, yeah, the, um--
  The straw.
  I apologize for the straw. Why you would build a house out of straw in the first place is a mystery to me, but--That's not my, uh--That's not the point. The point is, one of you wanted to build a house of straw, and I destroyed that house. I blew it down. Not that it takes much to blow down something made out of straw. A strong wind could have blown it down. A gust. A breeze. You built the house fairly close to the ocean, so I expect there would have been a lot of sea wind coming off the coast, and that leads me to think your house wasn't long for this world anyway, but sure, yes, I was the one who blew it down, and I have to own that, and so I do. I own it. I own it and I apologize for it. I blew down the house and I was going to eat you, but you ran away. I don't think I should have to apologize for wanting to eat you, because that's, you know, my nature, but I get how my nature and your existence don't jive, and I believe we should all be able to live together peacefully in this world, but I would like to remind you that eating, you know, kale, isn't really an option for me, and, uh, you know, attempted murder isn't murder. It's different. That's why they have a different sentence for it when you get convicted of it in court. When you do get convicted. Which isn't often, because it's so hard to prove. I mean, it's almost impossible to prove someone's intent, but, sure, I did attempt something, and for that, I am sorry, because that's wrong and so is blowing down a flimsy house that was going to come down at any moment anyway because somebody didn't want to take the time to build their home properly with decent materials.
  So. I'm sorry for all that.
  Um.
  In regards to the sticks, I would like to say that I maintain sticks are only slightly harder to blow down than straw, but there was, yes, an intent there, to blow the house down. And to eat the owner of the house. And to maybe use the sticks to start a fire that I would then roast the owner of the house over while lathering said owner in barbecue sauce. Yes, all of that is true, and none of it is right, and I apologize for all of it. I will say that because I couldn't catch the owner of the house, nothing happened other than destruction of a fire hazard, but nevertheless, there was destruction. There was trauma. There was hurt. And I have to understand that and make space for it moving forward. That I brought about and manifested hurt in the lives of swine. A fire could have hurt many more people. Not a nice fire that you can control while you cook your dinner, but a real fire that could start at any moment if some pig decided to light a candle in the middle of his twig dwelling, but it's not about what might have happened, it's about what did happen, and what happened was I blew the house down. I huffed. I puffed. I got a little winded. I huffed and puffed some more. Down went the house. I own that. I didn't eat the pig because he ran away, because somehow pigs are terrible at building houses, but they are fantastic at running away from wolves, so that's fine, he ran, I chased. And, uh, then…
  Then I hit a wall.
  A brick wall.
  We all have to hit that brick wall, don't we? Finally found a house I couldn't blow down. But you know what I could blow down?
  Myself.
  And that's what I did.
  I stood there and with all the breath in my furry body, I blew, and blew, and blew. But I could not blow that house down. And as I sat there, on the grass, the dew still fresh from morning, knowing that breakfast, lunch, and dinner was staring out a window from a brick house, mocking me, taunting me, and jeering at me, I knew I needed to take a good, hard look at my life and make some changes.
  That's why I'm here today--not at the end of my journey towards being a better creature, but somewhere in the middle. I'm asking for forgiveness. For the straw. For the sticks. Not for the brick, because that house was built well and I believe it got sold the following year for double what it cost to erect, and so, good on that pig, because he must have gotten the architecture gene his siblings didn't. Me, I'm just going around to different wolf packs, talking to the pups about making good decisions.
  Mostly I just tell them to stick to chickens.
  You tell them the sky is falling, and the next thing you know, they're walking right into your cave. No houses you need to gather up your breath support for and no riddles like with goats or grandmothers that give you indigestion. Just good, old-fashioned deception.
  So you see, I've learned.
  I've come a long, long way.", user: @user2, topic: @topic4)
@response5 = Response.create!(response: "I first saw her at a party sitting among the bohemian crowd, all skinny, all smoking, all intense with their words. She leaned forward with a glass of red wine in one hand, a cigarette in the other. She spoke as if in secret, telling them everything she knew of social injustice and political corruption, all the wrongs that they were certain in their hash-filled haze they could set right.
Stewart came from his bedroom, hugged me, took my suitcase and ragged coat before sitting softly beside her on the couch. His arm hung loosely around her shoulder as he watched her speak. This was the girl he had told me about. The one, he said. Suzanne. 
They took me in for several weeks and their two became three. We talked feverishly into the morning until the last drop of alcohol. He was a well-funded writer. She was trying to make it as a painter. I had been crashing with friends trying to finish my manuscript, but mostly I was drinking too much and running out of money.  She was neither coy nor hesitant like girls I had known. The ones who pretended to know less than they did. Who sat with perfect legs pointing toward garrulous unkempt boys, quietly waiting for the moment one would want to take her home.  
Stewart and Suzanne glided into the bedroom, arms around each other's waists, her lips like flower petals against his ears. I ached for her. 
I slid under the blanket on the old plaid couch. I couldn't sleep. I lit a cigarette. I thought of them together until I drifted into a drunken sleep. 
She was beautiful in the morning, boiling water for coffee and making eggs, taking drags from a joint at perfect intervals. Without Stewart I was speechless in her presence. I wrote in my notebook with a heavy head and waited for him to wake. She placed the coffee and eggs before me. Her slender  brown fingers touched everything with a tenderness my heart could not bear. 
I wrote about her. 
Six months after I first saw her we were standing at the train station waving goodbye to Stewart. He was leaving for Paris for a month to write. A graduation gift from a father he barely knew. 
“Be good,” he said to Suzanne brushing her soft black curls behind her ears. 
“I'll be back,” he said to me with a wink and a pat on the shoulder. 
Suzanne invited me to stay in her family's home on the coast of Maine to finish my manuscript. 
“You can write,” she said. “I can paint. I won't bother you.” 
The small white house stood at the shore. Wooden stairs led to a deck which gazed at the ocean. As I followed her up the stairs the wind forced waves to crash against rocks, showering us as Suzanne turned the key. Our shoes clacked against the wooden floor. I welcomed the silence after several nights of going away parties for Stewart. She showed me to my room, a perfectly tiny space with a twin bed and desk. Her room was right next door, our beds on opposite sides of the same wall. 
The kitchen cabinet was filled with wine and liquor. Suzanne pulled out two coffee mugs and filled them with bourbon. 
“Welcome,” she said, raising her mug to mine. 
The wind calmed, the clouds danced apart and the sunlight stretched its way into the kitchen where we sat on stools, sipping, smiling, silent. The bourbon warmed my tongue and melted its way down my throat, settling in my belly. 
She watched me for what felt like eternity, and I was desperate to find anything worth saying. I shooed away every worthless thought in my mind and felt relieved when she walked toward the record player. 
The back of her dress scooped low to her waist, and I fell in love with her back. I wanted to go to her and touch the back of her neck, running my fingers all the way down. I wanted to drop to my knees and kiss the small of her back. I wanted to make her forget Stewart.  I swallowed the bourbon whole. 
She put on a Miles Davis record and swayed her hips. Snapping her long fingers, her thrift store gems sparkled in the sunlight.  I lit a cigarette and poured more bourbon. 
“Dance with me,” she said as she swirled in my direction. 
“I can't,” I took a long pull from my cigarette and my bourbon. 
I tapped my foot to the beat and she danced her bare feet toward me. She finished off her bourbon and took a pull straight from the bottle. She wrapped her feathered scarf around my neck and laughed. Her perfect teeth. Her perfect eyes. My body weakened against her gentle tug and she pulled me up to my feet. 
We danced and I was lost. There was no house, no ocean, no floor beneath my feet. There was only us. Our foreheads pressed together. I closed my eyes, never wanting to look up. I pulled her close and she let me. Her head rested against the deafening beat of my heart. I let my fingers get lost in her hair and she looked up at me and stared. We swayed until after the record stopped. The house returned, and the wooden floor creaked with every movement. I moved to the kitchen table and lit another cigarette. 
“I'm drunk,” she laughed and swirled to the sound of wind and waves. 
I smiled and looked into my mug.  
She flipped the record over and slouched onto the couch. Sitting with her feet outstretched, she painted her toenails burgundy. I tried to write but it was all useless drivel. I should not have come, I thought. 
“Why have you been friends with Stewart for you so long?” she asked as she painted her smallest toe. 
“I don't know. We've been friends since we were kids. I've never really thought about not being friends with him I suppose.”  
“He told me that you were the smartest person he knows.” 
“I suppose Stewart needs more friends.” My attempted joke was met with silence. 
She sat upright and patted the seat next to her and like a dog I moved without thought, only sheer delight that she wanted me near her. 
We finished off the bottle and she told me about her family - her parents' divorce and her older brother who died in the war. She leaned her head on my shoulder as we passed the bottle back and forth. The muted trumpet sang to the ache of this moment and I wondered how it knew. I brushed back a lonely hair that rested on her forehead. She smelled of tangerines and bourbon and nail polish and everything I could love forever. 
It was still dark when I awoke.  Her sleepy head rested on my chest. I had to go to the bathroom, but I stayed still, staring at the softness of her hair, her skin, taking in every inch of a moment I did not deserve. 
She woke as the sun entered and walked to the bathroom, smoothing her dress and yawning. I made coffee, setting out a mug for each of us. I took my coffee and throbbing skull to my room to write. I pissed in a jug periodically so as not to have to face the pain of her beauty. 
We worked all day. She painted at her easel by the window facing the sea. I wrote in my room. In the evenings we ate and drank. She showed me her work. I read to her the bits I was not afraid to share. She was a compassionate reader with a talent for showing me where I had written too much or too little. She had the same disdain for useless words that I did though it did not seem as excruciating to her. 
When we sat close I could smell the oil paints she sat painstakingly with all day. Painting the red and orange and pink sunset, the moment that typically marked the end of our work. 
At sunset we cooked together and sat like husband and wife at the dinner table. And we danced. Every night we danced. She did not need to ask anymore. It became my role and I accepted the part. 
Our last night in the house I could not sleep. I thought of Suzanne and the love I could not give to her. Stewart would come home. He would ask her to marry him. She would say yes. They would have children. Our lives would drift apart. I would visit at Christmas and comment on how big their children were growing, how beautiful Suzanne's expecting belly looked. I would congratulate Stewart. A job well done. 
She was packing her paints and easel when I came out of the room.  I placed my suitcase by the door. The sun was barely winning its fight against the darkening clouds. 
We walked to the shore and sat with legs stretched toward the sea. The gulls mewed and circled the ocean. Suzanne wrapped herself in her paisley shawl, taking a drag from a joint. 
“It's so beautiful,” she said, passing the joint to me. 
“It is,” I said, taking a long pull, squinting my eyes toward the ocean, and waiting for the rain.", user: @user2, topic: @topic3)

puts "#{Response.count} responses created"

